#!/usr/bin/env python3
"""Reproduce src/unicode.almd from the pinned Unicode 15.0.0 category data.

Run with Python 3.12, whose unicodedata module embeds Unicode 15.0.0:
    python3.12 ci/generate_unicode.py > src/unicode.almd
Or verify without changing source:
    python3.12 ci/generate_unicode.py --check

Upstream data: https://www.unicode.org/Public/15.0.0/ucd/UnicodeData.txt
Version: https://www.unicode.org/versions/Unicode15.0.0/
License: ../LICENSE-UNICODE, from https://www.unicode.org/license.txt
This generator is original code; only Unicode category facts are derived.
"""
from pathlib import Path
import sys
import unicodedata

VERSION = '15.0.0'
LANGUAGE = 'java'
if unicodedata.unidata_version != VERSION:
    raise SystemExit(f'Requires Unicode {VERSION}; got {unicodedata.unidata_version}. Use Python 3.12.')


def category_ranges(categories):
    values = []
    start = None
    last = None
    for cp in range(128, 0x110000):
        if unicodedata.category(chr(cp)) in categories:
            if start is None:
                start = cp
            last = cp
        elif start is not None:
            values.extend((start, last))
            start = None
    if start is not None:
        values.extend((start, last))
    return values


start_categories = {'Lu', 'Ll', 'Lt', 'Lm', 'Lo', 'Nl'}
if LANGUAGE == 'java':
    start_categories |= {'Sc', 'Pc'}
continue_categories = start_categories | {'Mn', 'Mc', 'Nd', 'Pc', 'Cf'}
output = ('// Generated by ci/generate_unicode.py from Unicode 15.0.0 categories.\n'
          '// Source: https://www.unicode.org/Public/15.0.0/ucd/UnicodeData.txt\n'
          '// Copyright Unicode, Inc.; see LICENSE-UNICODE for the data license.\n')
for name, categories in [('starts', start_categories), ('continues', continue_categories)]:
    values = category_ranges(categories)
    output += f'fn {name}() -> List[Int] = [\n'
    output += ''.join('  ' + ','.join(map(str, values[i:i + 20])) + ',\n'
                      for i in range(0, len(values), 20))
    output += ']\n'
output += '''
fn contains(ranges: List[Int], cp: Int) -> Bool = {
  var lo = 0
  var hi = list.len(ranges) / 2
  var found = false
  while lo < hi and not found {
    let mid = (lo + hi) / 2
    if cp < (list.get(ranges, mid * 2) ?? 0) then hi = mid
    else if cp > (list.get(ranges, mid * 2 + 1) ?? 0) then lo = mid + 1
    else found = true
  }
  found
}
'''
if '--check' in sys.argv:
    path = Path(__file__).resolve().parents[1] / 'src/unicode.almd'
    if path.read_text() != output:
        raise SystemExit('Unicode data drift: regenerate src/unicode.almd')
    print(f'Unicode {VERSION} {LANGUAGE} tables match')
else:
    print(output, end='')
